name: Publish
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request: {}

env:
  Configuration: Release
  ProjectPath: src\Dotnet.Link\Dotnet.Link.csproj
  TestProjectPath: src\Dotnet.Link.Tests\Dotnet.Link.Tests.csproj

jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0.x
      - name: Restore
        run: dotnet restore ${{ env.TestProjectPath }}
      - name: Run Unit Tests
        run: dotnet test ${{ env.TestProjectPath }} --configuration ${{ env.Configuration }} --no-restore

  publish_beta:
    name: Publish Beta
    runs-on: windows-latest
    needs:
      - test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0.x
      - name: Restore
        run: dotnet tool restore
      - name: GitVersion
        run: dotnet gitversion /output buildserver
      - name: Build
        run: dotnet build ${{ env.ProjectPath }} --configuration ${{ env.Configuration }} -p:GeneratePackageOnBuild=false -p:Version=${{ env.GitVersion_AssemblySemVer }} -p:PackageVersion=${{ env.GitVersion_MajorMinorPatch }}-beta.${{ github.run_number }}
      - name: Pack
        run: dotnet pack ${{ env.ProjectPath }} --configuration ${{ env.Configuration }} --no-build -p:Version=${{ env.GitVersion_AssemblySemVer }} -p:PackageVersion=${{ env.GitVersion_MajorMinorPatch }}-beta.${{ github.run_number }}
      - name: Push
        run: dotnet nuget push src\Dotnet.Link\bin\${{ env.Configuration }}\*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

  publish_release:
    name: Publish Release
    runs-on: windows-latest
    needs:
      - test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0.x
      - name: Restore
        run: dotnet tool restore
      - name: GitVersion
        run: dotnet gitversion /output buildserver
      - name: Build
        run: dotnet build ${{ env.ProjectPath }} --configuration ${{ env.Configuration }} -p:GeneratePackageOnBuild=false -p:Version=${{ env.GitVersion_AssemblySemVer }} -p:PackageVersion=${{ env.GitVersion_SemVer }}
      - name: Pack
        run: dotnet pack ${{ env.ProjectPath }} --configuration ${{ env.Configuration }} --no-build -p:Version=${{ env.GitVersion_AssemblySemVer }} -p:PackageVersion=${{ env.GitVersion_SemVer }}
      - name: Push
        run: dotnet nuget push src\Dotnet.Link\bin\${{ env.Configuration }}\*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json